### ISSUE TITLE
Testing gmsh using tempfiles 

### ISSUE THREAD

**Issue by cbcoutinho** [nschloe/meshio#104]
Hi Nico,

I'm writing some gmsh tests for a model I'm developing, and I thought you may be interested as well (w.r.t meshio anyway). I want to have some example models built into the testing, and instead of carrying around .msh files, I'm using `tempfile.NameTemplateFile`s They work slightly better than text buffers, and are deleted after use automatically. This is a nice alternative to having .msh files lying around for me since I'm constantly writing over them - I thought you might be interested. This works on both py2 and py3 on my machine

Example:

```python
import meshio
import tempfile

gmsh_buffer = '''\
$MeshFormat
2.2 0 8
$EndMeshFormat
$PhysicalNames
5
1 1 "lower"
1 2 "right"
1 3 "upper"
1 4 "left"
2 5 "domain"
$EndPhysicalNames
$Nodes
9
1 0 0 0
2 1 0 0
3 1 1 0
4 0 1 0
5 0.499999999998694 0 0
6 1 0.499999999998694 0
7 0.5000000000020591 1 0
8 0 0.5000000000020591 0
9 0.5000000000003766 0.5000000000003766 0
$EndNodes
$Elements
12
1 1 2 1 1 1 5
2 1 2 1 1 5 2
3 1 2 2 2 2 6
4 1 2 2 2 6 3
5 1 2 3 3 3 7
6 1 2 3 3 7 4
7 1 2 4 4 4 8
8 1 2 4 4 8 1
9 3 2 5 1 1 5 9 8
10 3 2 5 1 8 9 7 4
11 3 2 5 1 5 2 6 9
12 3 2 5 1 9 6 3 7
$EndElements
'''

# Remember to remove indentation if the multi-line string is in a function
import textwrap
gmsh_buffer = textwrap.dedent(gmsh_buffer)


with tempfile.NamedTemporaryFile(suffix='.msh') as temp:
    temp.write(gmsh_buffer.encode('utf-8'))
    print(temp.name)
    temp.flush()
    points, cells, point_data, cell_data, field_data = meshio.read(temp.name)

(do all the things)
```

Cheers,
Chris

**Comment by nschloe** [comment]
Very nice! Perhaps this isn't so much for meshio (since the interfaces work based on file name strings right now, and you cannot re-open a `tempfile.NamedTemporaryFile()`), but it might be something for the temporary `geo` files in [pygmsh](https://github.com/nschloe/pygmsh/). Thanks for the hint anyways!

**Comment by cbcoutinho** [comment]
No worries, thought you might be interested

`tempfile.NamedTemporaryFile()` includes to option to not delete the generated file [link](https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile). It's true by default, but you can set it to False. I guess you could save a list of `temp.name`s to be deleted later if that's what you mean.

**Comment by gdmcbain** [comment]
Yes, I use `NamedTemporaryFile` with `delete=False` in my code where it interfaces to pygmsh.  Something like

    fp = NamedTemporaryFile(suffix='.geo', delete=False)
    fp.write(geom.get_code())
    fp.close()

    name = splitext(fp.name)[0]
    with open(name + '-out.log', 'w') as foutlog:
        with open(name + '-err.log', 'w') as ferrlog:
            call(['gmsh', '-%d' % dimension, fp.name],
                stdout=foutlog, stderr=ferrlog)

    mesh = meshio.read(name + '.msh')

where `geom` is a pygmsh.Geometry and `dimension` is 1, 2, or 3.

**Comment by nschloe** [comment]
@gdmcbain You are aware of `pg.generate_mesh(geom)`, right? In any case, if you absolutely need to call Gmsh manually, I'd recommend `-bin`. Not only is the I/O faster, there's also no information lost or added in the conversion process. (Unlike when using the decimal representation.)

**Comment by gdmcbain** [comment]
Ah, thanks for the reminder.  I had coded the above before nschloe/pygmsh#23.  I did introduce an alternative using `generate_mesh` immediately after it became available, but then the downstream code was still using my old method so I forgot about it.

Thanks for the tips about the binary format too; I hadn't thought about the decimal truncation in the ASCII output.  I always try use appropriate or dimensionless units so that that doesn't cause problems, but I do see it happening all the time elsewhere.
