### ISSUE TITLE
Implement mmg mesh format

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshio#118]
mmg uses the medit mesh format which is specified in the appendix of,
https://hal.inria.fr/hal-00681813/file/RT-422.pdf

**Comment by gdmcbain** [comment]
The MEDIT mesh format is at least partially supported by meshio.  I see that this is a very old question.  A fair bit of functionality was added since then in 2018 (#292, #297) to cope with the sudden switch of Gmsh to a new output format, MSH4 #280.

I'm not familiar with MMG.  Is this question still relevant?  If so, what features of MEDIT are missing?  Do they overlap with #239 or #295?

**Comment by kayarre** [comment]
@gdmcbain thank you for the follow up. I wrote this issue a while back, and at the time I don't think there was medit support. I have not tested meshio capabilities to read/write a medit file. I will test the lastest meshio  with a medit file generated with mmg  and if mmg can read a meshio generated medit file.

otherwise I would need to delve into the differences between the specification and meshio implementation which I have not done yet.

**Comment by nschloe** [comment]
Alright @kayarre, let us know if find something.

**Comment by nschloe** [comment]
Closing for now; feel free to reopen if something new comes up! :)
