### ISSUE TITLE
Manpage for meshio-convert

### ISSUE THREAD

**Issue by ghisvail** [nschloe/meshio#125]
@nschloe, I wrote a manpage for `meshio-convert` for the `meshio-tools` Debian package. I'd be happy to forward it upstream if you are interested. It is written in Markdown and converted using `pandoc`.

Please let me know.

**Comment by nschloe** [comment]
Sure, that'd make sense. Installing the man page probably can't be done via Python (since this is always cross-platform, and what are man pages in Windows?), see <https://github.com/pypa/packaging-problems/issues/72>. If you see a way, that'd be even better of course (if only for `debian/rules` hygiene).

**Comment by ghisvail** [comment]
Perhaps we could use your root Makefile or put it under `docs/` with a `Makefile` doing the `pandoc` call when running `make -C docs man`. That would be consistent with conventional Sphinx setups too.

**Comment by nschloe** [comment]
Sounds good!

**Comment by nschloe** [comment]
Any progress here?

**Comment by ghisvail** [comment]
The manpage is in the Debian packaging repository. Feel free to pick it up and incorporate it to your build system. I won't have time to do it myself unfortunately.

**Comment by nschloe** [comment]
Let's just keep it there then.
