### ISSUE TITLE
Vtk file can't be read if there is only mesh points (no associate data)

### ISSUE THREAD

**Issue by L4student** [nschloe/meshio#130]
I have a structured mesh as a [vtk file](https://github.com/nschloe/meshio/files/1338416/mesh.tar.gz) that contains only mesh points and there is no associated data in that file besides the nodes. Using `meshio.read('mesh.vtk')` gives the following error that ties to line 123 in `vtk_io.py` because it seeks `GetData()` in a file that does not have any:
```
# Explicitly extract points, cells, point data, field data
    points = numpy.copy(numpy_support.vtk_to_numpy(
            vtk_mesh.GetPoints().GetData()
            ))
```

Any suggestion? Could you include the capability to read just the mesh file? I was interested in converting vtk mesh to gmsh...so, if you think there will be further problems during conversion because of missing associated data then I would be interested to know. Thanks.

**Comment by nschloe** [comment]
All of meshio's data types revolve around _unstructured_ meshes, so no wonder this doesn't work. 

> Could you include the capability to read just the mesh file? 

I guess it would be possible to get something to work, but that part would be completely disconnected from everything else in meshio since there is no other structured mesh type I know of. Given that, I guess a reader could be another standalone program. Your best bet for now would be to take some inspiration from `vtk_io.py` in meshio and write it yourself.
