### ISSUE TITLE
vtu to gmsh exports inverted wedge node ordering

### ISSUE THREAD

**Issue by kayarre** [nschloe/meshio#185]
When reading in a vtu file with prisms, tetras, quads, and triangles,  the gmsh export of wedge elements has inverted node ordering. This gives negative jacobians down the pipeline.

I was able to correct this by using the following before writing to gmsh:
```
cells['wedge'] = numpy.roll(cells['wedge'], 3, axis =1)
```

(unsure if its an upstream vtk/vtu, meshio, gmsh issue?)

python script and vtu file.
[vmtkvtu2gmsh.py.zip](https://github.com/nschloe/meshio/files/1636590/vmtkvtu2gmsh.py.zip)

[DSI020CALb_vmtk_decimate_trim_ext2_mesh.vtu.zip](https://github.com/nschloe/meshio/files/1636595/DSI020CALb_vmtk_decimate_trim_ext2_mesh.vtu.zip)

Meshio I fantastic!

**Comment by nschloe** [comment]
Hm. VTK's wedge/prism node orderings are described at https://www.vtk.org/wp-content/uploads/2015/04/file-formats.pdf, and I cannot find such a thing for gmsh. Perhaps you could as at the gmsh mailing list if a particular node order for wedge elements is required?
Anyhow, when just converting the files everything seems fine.

**Comment by kayarre** [comment]
after looking into it it appears I was wrong, but here is the node ordering I found.

http://gmsh.info/doc/texinfo/gmsh.html#Low-order-elements
section 9.3.1



![gmsh_prism](https://user-images.githubusercontent.com/9031253/35021237-d8fd7176-fae4-11e7-80ab-330b44c72255.png)
![screen shot 2018-01-16 at 5 02 24 pm](https://user-images.githubusercontent.com/9031253/35021239-dbb37d7a-fae4-11e7-8534-167726495bd8.png)

**Comment by nschloe** [comment]
This is the same ordering (simply turn the gmsh wedge such that its 3 is at position 0 of the vtk mesh), so it seems there's nothing wrong here. The pyramid is the same as well. Hm. Perhaps a mistake in the Jacobian computation after all?

**Comment by kayarre** [comment]
I worked it out with an example.
it took the first wedge node values and mapped them.
based on the vtk ordering above the first wedge is [   0,    1,    2, 1609, 1610, 1611] and re-orienting the wedge as you described gives a ordering of [1609, 1610, 1611,    0,    1,    2] in the gmsh ordering.

This confirms what you get when using 
`numpy.roll(cells['wedge'], 3, axis =1)`

I may be missing something or don't understand? Thank you immensely for your time.

**Comment by nschloe** [comment]
I think I understand now. Earlier I didn't see a difference between

| ![wedge1](https://user-images.githubusercontent.com/181628/35061679-408cd1aa-fbc2-11e7-89bd-e28c489fb9e3.png) | ![wedge2](https://user-images.githubusercontent.com/181628/35061681-40a8ee76-fbc2-11e7-9fe3-caeff268738a.png) |
| ---- | --- |
| `[0 1 2 3 4 5]` | `[3 4 5 0 1 2]` |

– both  list two triangles, and the `k`th node of the first triangle is connected to the `k`th node of the second. (As a consequence, the normals of both triangles both point in the same direction.)

However, one requirement of gmsh and your own code seems to be that the second triangle normal points towards the first triangle. VTU and the mesh generator you used don't seem to care.

Okay, I'm not sure how to best deal with this. Three possibilities:

   * You fix your mesh generator.
   * You fix your own code to get the wedge ordering right.
   * When writing gmsh, we make sure that the ordering is "positive". Not sure if I'm a fan of this since then the conversion vtu -> gmsh -> vtu would have different inputs and outputs. In general I would like to mess as little as possible with the data.

The orientation of the wedge can be computed by, e.g.,
```
dot(cross(x2 - x0, x1 - x0), cross(x5 - x3, x4 - x3))
```
-- I'm sure there's a formulation without cross products, too.

**Comment by kayarre** [comment]
I think what makes sense is to go with fixing my own code.
I also think it would be nice to have some documentation of this behavior somewhere.
maybe this issue is sufficient record?

**Comment by nschloe** [comment]
> maybe this issue is sufficient record?

I would think so. Taking care of node ordering is one of the pitfalls of FEM implementations, and is not immediately due to how a mesh is read/written.

I still am curious if a "wrong" wedge is actually covered by the vtk and gmsh specifications. They both clearly only list the correct one, but neither ParaView nor gmsh's own display tool seem to care much if the ordering is the other way around. I've posted this on the VTK mailing list (https://www.vtk.org/pipermail/vtkusers/2018-January/100701.html), so let's see what gives. If you're motivated, you could do the same for gmsh.
