### ISSUE TITLE
dolfin XDMF: unable to recognise cell type

### ISSUE THREAD

**Issue by dajuno** [nschloe/meshio#260]
Hi,

the XDMF format created with meshio (by conversion of gmsh meshes) is not compatible with dolfin (although the deprecation warning for the dolfin-xml format recommends using XDMF).
The conversion seems to work, but the resulting XDMF file cannot be read in dolfin.

Dolfin error message:
```
*** Error:   Unable to recognise cell type.                                         
*** Reason:  Unknown value "mixed".
```
Best wishes
David

**Comment by nschloe** [comment]
Sounds like a FEniCS error to me.

**Comment by dajuno** [comment]
Have you seen this on the FEniCS slack?
https://fenicsproject.slack.com/archives/C2K9V55SA/p1529598166000183
Apparently FEniCS expects different cell types to be stored as separate items, not together as mixed.

**Comment by nschloe** [comment]
:+1: Let's discuss over there.

**Comment by a1650078** [comment]
As a workaround, it is possible to remove the non-tetrahedron cells with the `--prune` option.

**Comment by nschloe** [comment]
I'm thinking about fixing this. What I need is an XDMF file containing different cell types that actually works with FEniCS. Can anyone help out?

**Comment by a1650078** [comment]
I only use FEniCS occasionally and remember pulling out a lot of hair once upon a time trying to unravel fenics mesh imports - I actually switched to meshio when my old workflow stopped working. It turned out that (I think) with .xdmf imports (probably others, I don't know) the facet information is just not in the mesh file at all. Instead, facet information must be in a separate xdmf file defining a MeshValueCollection. I discovered this [reading about another issue](https://fenicsproject.org/qa/3237/default-meshfunction-created-sparse-meshvaluecollection/) but there is some documentation somewhere too. My workaround was to write a few lines of python code to recover the facets and create a FacetFunction from the cells manually. I think meshio generating this file would much easier to work with though

**Comment by gdmcbain** [comment]
> 👍 Let's discuss over there.

Unfortunately [there](https://fenicsproject.slack.com/archives/C2K9V55SA/p1529598166000183) I'm told
> Pour consulter l'historique complet de complet de cette cha&icirc;ne et y effectuer des recherches, vous devez passer &agrave; l'un de nos forfaits payants.

Did anything worthwhile transpire?  Meanwhile I'll see whether I can cook anything up here.

**Comment by nschloe** [comment]
Alright, so right now the only way of storing cells of different types in XDMF is with the `Mixed` type. Too bad that FEniCS cannot read it. That'd be a feature request for FEniCS though, not meshio.

I've filed a feature request over at XDMF for easier storage of different cell types (https://gitlab.kitware.com/xdmf/xdmf/issues/15), let's see what comes out of that.

Anyway, closing.
