### ISSUE TITLE
build tests fail: Connection refused to 127.0.0.1

### ISSUE THREAD

**Issue by RizzerOnGitHub** [nschloe/meshio#380]
A Debian build of 2.3.7 fails during build tests on test_reference_file.

The build appears to be assuming 127.0.0.1:9 is available for connections, but it is not.

Build log attached.

[python-meshio_2.3.7-1_amd64.build.gz](https://github.com/nschloe/meshio/files/3124752/python-meshio_2.3.7-1_amd64.build.gz)

**Comment by RizzerOnGitHub** [comment]
Also failing to connect to nschloe.github.io:443

**Comment by nschloe** [comment]
Hm, yes. Since recently, meshio has some tests against reference mesh files. Those files, being heavy data, are not included in the meshio repository to avoid a blowing-up in size. Instead, they are downloaded at test time from an online source (the orphaned gh-pages branch of meshio on GitHub). That's probably what's causing the issue.

Not sure how to best proceed here.

**Comment by RizzerOnGitHub** [comment]
Is it just 

    msh/insulated-2.2.msh
    msh/insulated-4.1.msh
    med/cylinder.med
    vtk/rbc_001.vtk
in https://nschloe.github.io/meshio/ ?

Only 68 KB there.

But I don't think https connections are necessarily blocked by the build system, I think it's possible to make the links work. Maybe some other configuration setting is needed.

**Comment by nschloe** [comment]
> Only 68 KB there.

That's right. The idea was to allow larger files, too, which is why the it was set up this way. I'm not entirely happy with it, though.

**Comment by gdmcbain** [comment]
I'll chime in here, feeling partly responsible after having suggested a test suite for readers #335 in the first place.

I had worried that something like this might happen, but didn't know how realistic that was.  There was a [gripe](https://github.com/nschloe/meshio/pull/365#issuecomment-475858880) about it in #365, followed by a [rationale](https://github.com/nschloe/meshio/pull/365#issuecomment-476164858).  The former had suggested a directory in the master branch while the latter recalled bad experience with Trilinos:

> Not only does everyone who ever uses Trilinos have to download the meshes, even if having no intention of running the tests. What's worse is that the meshes are forever engraved in git history, so pulls are terribly slow even if the meshes are removed now.

The first part of this could be partially alleviated by having the suite of meshes in a directory in the master branch that is not installed by pip.   I haven't seen the statistics, but I imagine many who use meshio install it via pip, perhaps unknowingly if brought in as an automatic dependency by e.g. pygmsh.  (I was initially in that subset myself.)  Currently what is installed by pip is controlled by `packages=find_packages()` in `setup.py` and this only installs the `meshio` directory, not `logo`, `test`, &c., I think because they don't contain an `__init__.py` file.  (Or does pip download everything and then just install some?  I hope not, but I haven't checked.)

But I assume that that has already been considered.  Another idea then: what about a separate package on PyPI?  Say 'meshio-test-suite', not depended on by default, but listed in `test_requirements.txt` or similar.  Would it be reasonable to assume that even though https is unavailable to the builder, pip can be used to bring in dependencies?  Or do all dependencies have to be installed Debian-style?  If so, I don't understand that well enough to comment.

**Comment by RizzerOnGitHub** [comment]
A separate test package (or demo package) is not a bad idea, and provides a robust and simple solution (assuming paths can be agreed on. Something like /usr/share/meshio/test-suite makes sense).

What we'd do in Debian is package it as another package, which the meshio package would then depend on (Build-Depends).

**Comment by nschloe** [comment]
Okay, I think the easiest thing to do for now is to patch out the respective tests in Debian. @RizzerOnGitHub Feasible?

**Comment by RizzerOnGitHub** [comment]
We can put a patch in debian/patches.  Can you provide a preferred patch?

**Comment by nschloe** [comment]
Just comment out all the `test_reference_file` tests.

**Comment by RizzerOnGitHub** [comment]
I see. Can do.

**Comment by RizzerOnGitHub** [comment]
Interesting discussion about Debian's policy on build-time net access. Some say it's too strict, but others say it's there for a reason (e.g. averting security risks).  https://lwn.net/Articles/700465/

The Debian policy on net access during build is articulated at https://www.debian.org/doc/debian-policy/ch-source.html#main-building-script-debian-rules

**Comment by nschloe** [comment]
I've now switched meshio to Git LFS, so the `download()` isn't necessary anymore.

**Comment by RizzerOnGitHub** [comment]
LFS is a good solution for this. The LFS reference files remain in the github tarballs (there's a github discussion [elsewhere](https://github.com/git-lfs/git-lfs/issues/1322) about that). I don't know if that's a problem for pypi.  The meshes subdir is missing in the pypi tarball.

We're discussing how to best handle LFS with the Debian repos.
https://lists.debian.org/debian-devel/2019/08/msg00224.html
There's a new tool pristine-lfs which might help us.

**Comment by nschloe** [comment]
> I don't know if that's a problem for pypi.

Yeah, one probably cannot run the respective tests from the pypi tarball. I wouldn't consider this is a huge problem though, at least so far no one has complained.

From the discussion on the Debian list it seems that the problem is solved. If not let me know if there's anything else I can do.

**Comment by RizzerOnGitHub** [comment]
For Debian, I changed debian/watch to get source tarballs from git tags instead of the github "release" tarballs. That method enables access to your LFS objects.  I've also configured the debian repo to use LFS, copying your LFS configuration.   So the Debian packaging is fine now.

**Comment by nschloe** [comment]
Let's close this then. Feel free to comment/reopen if the problem reoccurs.
