### ISSUE TITLE
MSH 4.1: nodes have wrong tags in some cases

### ISSUE THREAD

**Issue by mrambausek** [nschloe/meshio#388]
When reading the msh-file attached, the node labels (tags) are ignored, leading to silently corrupted data. In the example attached, this means that, e.g., node 11 ends up as node 6.
[reading_failure.msh.zip](https://github.com/nschloe/meshio/files/3196818/reading_failure.msh.zip)

**Comment by mrambausek** [comment]
The issue is related to these lines of code in ``msh_io/msh4_1.py`` in function ``_read_nodes``.
```
if is_dense:  
    fromfile(f, c_size_t, num_nodes)  
else:  
    tags[ixx] = fromfile(f, c_size_t, num_nodes) - 1  
```
The file attached in the original description is identified as dense, but doe not have uniformly increasing tags.

**Comment by gdmcbain** [comment]
Thank you for providing a nice small example.  I'm looking into it now.  Could you tell us how it was generated?  From a .geo file?  By which version of Gmsh?  Thanks.

**Comment by gdmcbain** [comment]
I see, yes, the nodes in the MSH file are numbered from `minNodeTag == minElementTag == 1` to `numNodes == maxNodeTag == 29`, but not in order, rather 1, 2, 3, 4, 5, 11, 12, 6, 13, 14, 7, 15, 16, 8, 17, 18, 9, 10, and then 19 through 29.  I note that this is permitted in the [specification](http://gmsh.info/dev/doc/texinfo/gmsh.html#MSH-file-format):
> All the node, element and entity tags (their global identification numbers) should be strictly positive. (Tag 0 is reserved for internal use.) Important note about efficiency: tags can be "sparse", i.e., do not have to constitute a continuous list of numbers (the format even allows them to not be ordered).

however, it does go on to say that

> By default, for non-partitioned, single file meshes, Gmsh will create files with a continuous ordering of node and element tags, starting at 1.

Do you know how it came about that the node tags aren't ordered here in this non-partitioned single-file mesh?  Coping with this might require a substantial change in `meshio.msh_io.msh4_1`.

I suppose it's required that what Gmsh calls node 11 turns up as `.points[11 - 1]` in the `Mesh` returned by `meshio.read`?  Rather than merely that the elements connected to node 11 turn up as cells connected to a point at the same coordinates, viz. `[.25, 0., 0.]`)?

**Comment by mrambausek** [comment]
Okay, it is a very nice subtle thing:
The .geo file consists of three instructions:
``SetFactory("OpenCASCADE"); Rectangle(1) = {0, 0, 0, 1, 0.5, 0}; Transfinite Curve {1, 2, 3, 4} = 3 Using Progression 1;``
 
With Gmsh v4.2 running ``gmsh -2 -order 2 failure.geo`` gives dense ordering, indeed.
However, when using the graphical interface, meshing 2d and then setting order to 2, the resulting file
does not have dense ordering. So it seems, at least Gmsh v4.2 does not grant dense ordering.

> I suppose it's required that what Gmsh calls node 11 turns up as .points[11 - 1] in the Mesh returned by meshio.read? Rather than merely that the elements connected to node 11 turn up as cells connected to a point at the same coordinates, viz. [.25, 0., 0.])?
Well, from my understanding, node 11 can be relabeled, as long as this change is reflected in the connectivity. However, it would probaly be nice to not change these labels for consistency with what the user sees when examining .msh files with gmsh. Did I understand the question correctly?

**Comment by gdmcbain** [comment]
Ha, I see.  Thanks for that.  Interesting!  I'll take a crack at this next week if nobody beats me to it.

Your example might be a candidate for the test-suite #335.

**Comment by gdmcbain** [comment]
I'm able to reproduce the problem (nodes tagged …, 5, 11, 12, …) in the latest Gmsh from git master, version 4.4.0-git-bea1e5dde, but, as you say, only in the graphical interface, not via the command-line.

**Comment by gdmcbain** [comment]
I think this'll have to be fixed here anyway, but I reported it to the Gmsh list too.

 http://onelab.info/pipermail/gmsh/2019/013105.html
