### ISSUE TITLE
meshio-convert problem from .exo to .vtk

### ISSUE THREAD

**Issue by gahansen** [nschloe/meshio#401]
When processing the attached exodus example (`meshio-convert fblock_restart.exo fblock_restart.vtk`), none of the cell data present is read from the exo file and transferred to the vtk file. Paraview will open and visualize the exodus file and show several cell data fields in the original data (stresses and strains).

[fblock_restart.exo.zip](https://github.com/nschloe/meshio/files/3398604/fblock_restart.exo.zip)

**Comment by nschloe** [comment]
Hi Glen!

I've just merged #405 to tackle the problem. Some issues remain:
   * There is no support for time-data for exodus yet, so it just takes the data belonging to the first time step. VTK doesn't have support  for time steps either, so it wouldn't do any good anyways.
   * VTK doesn't support spaces in variable names, so you cannot convert to VTK. VTU works.
   * There is no support for element blocks in meshio (and most mesh formats), so that information is not retained.
   * The stresses and strains are named `Stress xx_ave`, `Stress xy_ave` etc., which I guess should indicate they all belong to the same 3x3 `Stress_ave` field. Not sure why exodus doesn't treat them as one.

**Comment by gahansen** [comment]
Hi Nico!

Thanks much for doing this, it appears to work perfectly for my needs! I did use the vtu format which is just fine, and I also checked the xdmf format which also works from what I can see.

I think the host code wrote the stresses into the exodus file in this manner, there is probably a more efficient way of doing this in exodus than that. But, the result looks great for what I need.

Thanks again, I will close this issue.
