### ISSUE TITLE
treat gmsh's physical groups

### ISSUE THREAD

**Issue by nschloe** [nschloe/meshio#43]
[The Gmsh data format](http://geuz.org/gmsh/doc/texinfo/gmsh.html#MSH-ASCII-file-format) offers several of data fields, e.g., `ElementData`, `NodeData` etc. On top of that, there a "Physical Groups", effectively tagging entities. It's not quite clear yet where this information fits in with other mesh formats.

**Comment by nschloe** [comment]
@dajuno, can you provide an example file with physical groups?

**Comment by dajuno** [comment]
nschloe, I will in january, going on a small trip now =)
Cheers

**Comment by dajuno** [comment]
@nschloe, here's a simple 3D example with physical surfaces and a physical volume: https://gist.github.com/dajuno/691fa18db83f7b36db5c
(Unit cube where all 6 surfaces are tagged differently.)
And with a cylindrical subdomain: https://gist.github.com/dajuno/6545e964cf9c499dc4e1
I.e., there are 2 physical volumes. The physical surfaces are the cylindrical surface (interface), and the outer surfaces (front and back separated into circle and "cut out" cube).

gmsh has physical lines and points, too. Relevant for 2D cases.

Until now, in order to convert the gmsh mesh to HDF5 I have been using `dolfin-convert` to convert to XML, creating mesh.xml, mesh_facet_region.xml & mesh_physical_region.xml, and then a small script using the dolfin functions to create a hdf5 mesh, based on:
```
from dolfin import *
mesh = Mesh('mesh.xml')
subdomains = MeshFunction("size_t", mesh, "mesh_physical_region.xml")
boundaries = MeshFunction("size_t", mesh, "mesh_facet_region.xml")

# Write HDF5
hdf = HDF5File(mesh.mpi_comm(), "mesh.h5", "w")
hdf.write(mesh, "/mesh")
hdf.write(subdomains, "/subdomains")
hdf.write(boundaries, "/boundaries")
```
and
```
# Read HDF5
mesh = Mesh()
hdf = HDF5File(mesh.mpi_comm(), "mesh.h5", "r")
hdf.read(mesh, "/mesh", False)
subdomains = CellFunction("size_t", mesh)
hdf.read(subdomains, "/subdomains")
boundaries = FacetFunction("size_t", mesh)
hdf.read(boundaries, "/boundaries")
```
taken somewhere from the fenics Q&A.

Let me know if you need more info or if I can be of any help!

**Comment by dajuno** [comment]
> It's not quite clear yet where this information fits in with other mesh formats.
@nschloe don't other mesh formats allow for "tagging" of subdomains or boundaries?

**Comment by nilswagner** [comment]
In PERMAS you might use $PART, $ESET to structure the model.
A group of elements can be directly assigned to an element set within its
definition $ELEMENT.

**Comment by gpkc** [comment]
This is actually very important to gmsh users. It`s a very straightforward way to set boundary conditions, for example. This should not be neglected probably. A workaround would be to add new entries on the cells dictionary, for the elementary, physical, partition tags etc, relating elements ids to those tags.

**Comment by nschloe** [comment]
Fixed now.
