### ISSUE TITLE
Physical groups for msh4.1 mesh

### ISSUE THREAD

**Issue by MEMAndersen** [nschloe/meshio#444]
I am having problems figuring out how to use physical_groups / regions from a .msh v 4.1 mesh. I have looked around for documentation on this but i cannot seem to find anything, and just looking at the plain code is not enough for me to figure it out. Would anybody be willing to show me how to extract the elements for the physical group "north" for this mesh?

https://pastebin.com/Apdwd5Ak

Sorry if this is not the intended fora for a question like this.

**Comment by keurfonluu** [comment]
It seems that physical group 6 ``"north"`` is associated to 2D elements (triangles).

Gmsh physical groups are stored in ``mesh.cell_data`` as an integer array under the keyword ``"gmsh:physical"``. In your case, 2D physical groups are stored in ``mesh.cell_data["triangle"]["gmsh:physical"]``, elements for group 6 ``"north"`` are labeled as 6. In order to extract elements for physical group ``"north"``, you can look for all the elements labeled as 6 in ``mesh.cells["triangle"]`` following:

``` python
mesh.cells["triangle"][mesh.cell_data["triangle"]["gmsh:physical"] == 6]
```

Last but not least, physical group names are stored in ``mesh.field_data``.

**Comment by MEMAndersen** [comment]
Thank you very much keurfonluu! This was a great help. Just for curiosity is there no documentation for this kind of question anywhere? The only documentation i can find is https://www.pydoc.io/pypi/meshio-2.0.0/ which is outdated. If help is needed for this i would like to help draft documentation for msh 4.1 since i'm quite familar with this format.
`mesh.cells["triangle"][mesh.cell_data["triangle"]["gmsh:physical"] == mesh.field_data['north'][0]]`

**Comment by nschloe** [comment]
For the record, pydoc.io is not associated with meshio. No idea who set this up, but yeah, it's no help. Meshio doesn't have a proper doc except for the main readme because it's such a simple module.

**Comment by MEMAndersen** [comment]
That is fair, i feel like the above syntax is not that obvious but that could just be me :). 
Thanks for a great library :)!
