### ISSUE TITLE
Abaqus 2D & element type

### ISSUE THREAD

**Issue by kip-hart** [nschloe/meshio#501]
**2D**
I'm interested in using/inheriting from meshio in my project, which generates 2D and 3D meshes. Abaqus input files can contain 2D meshes, so I'm not sure why there is this code in the `write` function:

https://github.com/nschloe/meshio/blob/master/meshio/_abaqus.py#L250-L257

A 2D mesh should have coordinates (x, y) rather than (x, y, 0). The output file would need to be post-processed to remove the 3rd coordinate.

**Element Type**
It would also be nice to specify the element types when writing the input file. For example, a dictionary like `meshio_to_abaqus_type` could be (optionally) passed into the write function.
This would also eliminate the need for post-processing with a find/replace on the element types.

I'd be willing to fork and edit if you'd like, just let me know. This issue appears to be similar to #320.

**Comment by nschloe** [comment]
> so I'm not sure why there is this code in the write function:

I added this last year https://github.com/nschloe/meshio/commit/06fbef45470a878c77ac02ed696b379de3c62040, but didn't give a reference. It's a problem that I don't have a specification for Abaqus INP files. Do you know where to find it?

> It would also be nice to specify the element types when writing the input file.

I don't understand -- you can already do that, no? The cells are a dictionary like `{"triangle": ..., "tetra": ...}`.

**Comment by tianyikillua** [comment]
Concerning writing 2d spatial coordinates, yes if Abaqus accepts pure 2d coordinates, additional padding is not necessary.

I get your point concerning element types in output. The problem is that the map between meshio mesh types and elements types supported by Abaqus is not one-to-one (but also for many other finite element simulation-centric mesh formats). For generic triangles elements, several Abaqus elements are available
```
abaqus_to_meshio_type = {
    ...
    "STRI3": "triangle",
    "S3": "triangle",
    "S3R": "triangle",
    "S3RS": "triangle",
    ...
```
Due to `meshio_to_abaqus_type = {v: k for k, v in abaqus_to_meshio_type.items()}`, currently the last corresponding Abaqus element `S3RS` will be used in output.

The idea is to expose `meshio_to_abaqus_type` in the `write` method, or introduce an additional dictionary `user_meshio_to_abaqus_type` that modifies `meshio_to_abaqus_type`
```
for key in user_meshio_to_abaqus_type:
    if key in meshio_to_abaqus_type:
        meshio_to_abaqus_type[key] = user_meshio_to_abaqus_type[key]
```

**Comment by nschloe** [comment]
Got it. I'm on it right now.

**Comment by nschloe** [comment]
Okay, tentatively fixed. This now works:
```python
import meshio

points = [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0]]
cells = {"TRI3": [[0, 1, 2]]}

meshio.write_points_cells("out.inp", points, cells, translate_cell_names=False)
```

**Comment by kip-hart** [comment]
Thanks all - this is great! For future reference, there are a few websites with Abaqus documentation. The [Abaqus/Standard Element Index](https://abaqus-docs.mit.edu/2017/English/SIMACAEELMRefMap/simaelm-c-stdelementindex.htm) has a full listing of the element types, node numberings, etc.
