### ISSUE TITLE
vtk io with python3

### ISSUE THREAD

**Issue by timmyL17** [nschloe/meshio#53]
When loading a vtk file using python3, there is an iteritems() call in vtk_io.py

>>> points, cells, point_data, cell_data, field_data = meshio.read('output_95.vtu')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/meshio/__init__.py", line 83, in read
    return vtk_io.read('vtu', filename)
  File "/usr/local/lib/python3.5/site-packages/meshio/vtk_io.py", line 96, in read
    )
  File "/usr/local/lib/python3.5/site-packages/meshio/vtk_io.py", line 54, in _read_cells
    #for vtk_type, meshio_type in vtk_to_meshio_type.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

Maybe we could use the future library to make the code compatible with python2 and python3?

**Comment by nschloe** [comment]
Sure thing! The reason why I haven't properly done this is that only since recently, VTK's Python support includes Python 3 (7.0 onwards). It hasn't landed in Debian yet, so I didn't get the chance to test it.

If you have VTK 7.0+ installed, you're probably the best tester. Let me know if replacing `iteritems()` is already enough. A PR of course would be great!

**Comment by timmyL17** [comment]
Great, yes just replacing iteritems seems to make everything work. I can make a PR. Are you ok with requiring the future module? I guess it's not part of the standard distribution (but easily available through pip).

**Comment by nschloe** [comment]
Closing via https://github.com/nschloe/meshio/pull/55.
