### ISSUE TITLE
Clarify CI procedure

### ISSUE THREAD

**Issue by clbarnes** [nschloe/meshio#596]
The new multi-version stuff is handled by github actions, but the PR still seems to be gated on the outcome of circleci jobs. As per #543, can we just have one?

**Comment by nschloe** [comment]
So you might know that gh-actions came out just a few weeks ago. I'm eager to use it because circleci is very slow from time to time. I would not like to make the switch immediately, but have the two systems run side-by-side for testing for a while. (Perhaps gh-actions is also slow at times.)

Also, we'll have to hold out for the ecosystem to settle. https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/9
