### ISSUE TITLE
meshio.read() error with STL format

### ISSUE THREAD

**Issue by MoiseRousseau** [nschloe/meshio#641]
Hi all,

I am using meshio version 3.3.1 with python 3.7.5 on Ubuntu 19.10 to convert an STL ASCII file to an OBJ file. I got a problem when trying to read the STL file (in attachment and rename into txt - [frontier.txt](https://github.com/nschloe/meshio/files/4098170/frontier.txt) ). 

Here is my terminal output:
```
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import meshio
>>> meshio.__version__
'3.3.1'
>>> mesh = meshio.read('frontier.stl', file_format="stl")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moise/.local/lib/python3.7/site-packages/meshio/_helpers.py", line 67, in read
    return reader_map[file_format](filename)
  File "/home/moise/.local/lib/python3.7/site-packages/meshio/stl/_stl.py", line 39, in read
    out = _read_ascii(f)
  File "/home/moise/.local/lib/python3.7/site-packages/meshio/stl/_stl.py", line 102, in _read_ascii
    usecols=(1, 2, 3),
  File "/home/moise/.local/lib/python3.7/site-packages/meshio/stl/_stl.py", line 61, in iter_loadtxt
    data = numpy.fromiter(iter_func(), dtype=dtype)
  File "/home/moise/.local/lib/python3.7/site-packages/meshio/stl/_stl.py", line 58, in iter_func
    yield dtype(items[idx])
ValueError: could not convert string to float: 
>>> 
```

The STL file was created by Salome software, and seems OK as I can read it into MeshLab to convert it.

Please let me know if you need more information.
Moise

**Comment by gdmcbain** [comment]
It seems that the (ASCII) STL contains two spaces between items on a line defining a vertex; e.g. line 4:
```
     vertex  0.000000e+00  1.000000e+03  0.000000e+00
```

I don't know whether this is valid or not, but it would seem reasonable for meshio to accept it if MeshLab does.  (Gmsh does too.)  

The double space is not expected by `iter_func`; 
https://github.com/nschloe/meshio/blob/f198c3432ec58b99f82fc4272196b2e664e49eb3/meshio/stl/_stl.py#L55
turns the above into
```python
['vertex', '', '0.000000e+00', '', '1.000000e+03', '', '0.000000e+00']
```
and then the coordinates are not in 
https://github.com/nschloe/meshio/blob/f198c3432ec58b99f82fc4272196b2e664e49eb3/meshio/stl/_stl.py#L102

I think the fix is to make `iter_func` a bit more robust.  A quick fix is just
```python
items = line.split()
```
which gives
```python
['vertex', '0.000000e+00', '1.000000e+03', '0.000000e+00']
```

Is the more general `delimiter` required?
