### ISSUE TITLE
XDMF writer with vertex cells crashes ParaView

### ISSUE THREAD

**Issue by adtzlr** [nschloe/meshio#651]
Hello,

the following MWE causes ParaView to crash. It happens if vertex cells use their own nodes (not connected to the grid used by quads):

```python
import numpy as np
import meshio

filename = 'test.xdmf'

nodes= np.array([0,0,0, 
                 1,0,0,
                 2,0,0,
                 0,1,0, 
                 1,1,0,
                 2,1,0,
                 0.5,0.5,0,
                 1.5,0.5,0], dtype=float).reshape(-1,3)

connectivity = np.array([[0,1,4,3],
                         [1,2,5,4]])

conn = np.array([[-2],[-1]])
# change to 
# conn = np.array([[-4],[-3]])
# and it works....

cells = {'quad': connectivity, 'vertex': conn}

with meshio.xdmf.TimeSeriesWriter(filename) as writer:
    writer.write_points_cells(nodes, cells)
    
    for time in np.linspace(0,1,10):

        cell_data = {
                    'hexahedron': 
                    {'stress': np.random.rand(len(connectivity),6)},
                    'vertex': 
                    {'stress': np.random.rand(len(conn),6)}
                    }
        
        disp = np.random.rand(*nodes.shape)
        disp[:-1] = np.nan
            
        point_data = {'Displacement': disp}
        
        writer.write_data(time, 
                          point_data=point_data, 
                          cell_data=cell_data)
```

However, if vertex cells re-use nodes from quad elements, everything is fine. My idea was to add vertex cells as fake quadrature points to export my stresses, strains, kinematic variables at the correct location from my FE code. Beside this export problem in meshio - do you have any better ideas for that?

Best regards,
Andreas

**Comment by keurfonluu** [comment]
You can display your displacement vectors as arrow glyphs.

**Comment by adtzlr** [comment]
@keurfonluu Thank you for your answer. I think however you misunderstood me. I know I can display displacements - or in general any node related data - as point data. I was thinking of exporting stresses for linear quadrilaterals at their calculated gauss points. The other way round would be to interpolate the gauss point data to the nodes, perform nodal averaging and export them also as point data with meshio. I thought I could use some magic of meshio or paraview for that :-) .

BR Andreas

**Comment by gdmcbain** [comment]
I don't have any better ideas of how to handle data at quadrature points.  It is an interesting question.  I can't think of any mesh formats that explicitly support it. I'm sure some do.  XDMF doesn't.  If you want to use XDMF, then vertices seems reasonable.

Anyway though there's a different problem with your example.  Even if I omit all the data and just work with the points and cells, it crashes ParaView 5.6.0 (Ubuntu 19.10) with either of the versions of `conn`.  I think there are a couple of things going on.

1. I'm not sure how well XDMF polyvertices are supported in meshio as part of `TopologyType="Mixed"`.  They do work as part of  `TopologyType="Polyvertex"`, but then we run into #568.  That would suggest the immediate expedient of saving multiple XDMF, one for the quads and one for the vertices.  That avoids the dreaded mixed topology.

2. There's cell_data for 'hexahedron' but no hexahedra in `cells`, only `'quad'` and `'vertex'`.  That doesn't look right.

3. But before that, I'm at the negative indices in `conn` for `cells['vertex']`; are they supposed to work in XDMF?

If I modify them so that they're mod `nodes.shape[0]`, and skip the `point_data` and `cell_data` for the moment, the preceding idea of multiple XDMF works:

```python
for k, v in cells.items():
    if k == 'vertex':
        v %= nodes.shape[0]
    meshio.write(f'{k}.xdmf',
                 meshio.Mesh(nodes, [(k, v)]),
                 data_format='XML')
```

(Note: `data_format='XML'` for more easily inspected MWEs.)

(Note: I'm on meshio master so `cells: List[Tuple[str, ndarray]]`.)

**Comment by gdmcbain** [comment]
Another MWE, focussing on vertices written by meshio to XDMF:
* correctly with `TopologyType="Polyvertex" but
* incorrectly with `TopologyType="Mixed"`, crashing ParaView

```python
import numpy as np
import meshio

points = np.array([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0]])
cells = [("vertex", np.array([[0], [1]])), ("line", np.array([[0, 1]]))]

meshio.write("mixed.xdmf", meshio.Mesh(points, cells), data_format="XML")

for cell_type, cell_block in cells:
    meshio.write(
        f"{cell_type}.xdmf",
        meshio.Mesh(points, [(cell_type, cell_block)]),
        data_format="XML",
    )
```

This generates:
* [vertex.xdmf.txt](https://github.com/nschloe/meshio/files/4150656/vertex.xdmf.txt)
* [line.xdmf.txt](https://github.com/nschloe/meshio/files/4150657/line.xdmf.txt)
* [mixed.xdmf.txt](https://github.com/nschloe/meshio/files/4150658/mixed.xdmf.txt)

of which the first two are happily rendered by ParaView 5.6.0 while the last brings it down.

**Comment by gdmcbain** [comment]
If `mixed.xdmf` is edited to specify the number of vertices in each Polyvertex, it's fine; i.e. either
```xml
<Topology NumberOfElements="3" TopologyType="Mixed"><DataItem DataType="Int" Dimensions="10" Format="XML" Precision="8">
1 1 0
1 1 1
2 2 0 1
</DataItem></Topology>
```
or
```xml
<Topology NumberOfElements="3" TopologyType="Mixed"><DataItem DataType="Int" Dimensions="8" Format="XML" Precision="8">
1 2 0 1
2 2 0 1
</DataItem></Topology>
```

**Comment by gdmcbain** [comment]
A fix for `XdmfWriter` is proposed #652; something similar should work for `TimeSeriesWriter` too.

**Comment by adtzlr** [comment]
Thank you for your ideas, although I do not understand everything you wrote :blush: . I have to apologize as I made 2 mistakes in the initial MWE posted by me: I did by mistake wrote negative indices for the connectivity matrix as I'm totally used to it in Python. That was not my intention and ParaView also crashed with positive connectivity indices. Also the dummy cell data should contain `quad` and not `hexahedron` as key for the `cell_data.` Sorry for that.

Regarding two seperate XDMF files: Thank you for the hint, will have a look at it!

And for further explanation of my idea: I thought I could export the element-based gauss point data (like stresses) and "map" them to the nodes in ParaView for visualization. Although this should be possible by the filter "resample with dataset" I'm stuck because actually no resampling is performed - there must be a problem with the tolerance of detecting neighbour nodes - but this is truly not meshio related...

**Comment by gdmcbain** [comment]
> Thank you for your ideas, although I do not understand everything you wrote 

You're welcome and sorry if it was garbled, it was written on the fly.  Do feel free to ask further questions.

I think we can close this issue since the essential problem was the handling of Polyvertex in XDMF TopologyType="Mixed" and that was fixed in #652.  Dealing with data defined on integration points is interesting but separate; let's open a new issue if an aspect relating that to meshio arises?  (It rather falls under what was [recently called ‘fem-io’](https://github.com/nschloe/meshio/issues/630#issuecomment-572260040), i.e. out of scope for meshio.)  For that I guess we'd need an existing file format that actually supports quadrature points; I don't think XDMF, Exodus, or even Silo #659 does. (I'm sure I've heard of that somewhere but can't recall where.)

**Comment by tianyikillua** [comment]
For information, the MED format supports storing internal variables at Gauss points.

https://www.code-aster.org/forum2/viewtopic.php?id=23129
https://docs.salome-platform.org/latest/dev/MEDCoupling/developer/med-file.html

For visualization under salome/paravis (a plugin to ParaView in fact), these fields are simply displayed on Gauss points.

**Comment by adtzlr** [comment]
@tianyikillua Thanks for the hint. But let me guess: Writing gauss point data in MED is not (yet :sunglasses: ) possible through meshio?

**Comment by tianyikillua** [comment]
@adtzlr Well actually it does partially: if you read the code, cell fields have shape `(n_cells, n_gauss_points, n_components)`. However the location of those Gauss points are not read, although it would be simple to do so I guess.
