### ISSUE TITLE
ENH: int_data_to_sets

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/meshio#716]
The dream: to work with a `meshio.Mesh` without worrying about which file format it was `meshio.read` from.  Specifically: extract the tagged subsets of cells #290 without worrying about whether they're defined explicitly in `.cell_sets` or implicitly in int-valued functions in `.cell_data`—and in the latter case whether the key is `"gmsh:physical"`, `"medit:ref"`, …

There was a previous proposal to include int-valued `.cell_data` in the `Mesh.cell_sets_dict` property #715; this was discussed and rejected in favour of a function to convert the int-valued data to sets, perhaps called ‘`convert_int_data_to_set`’.  The returned value should have the same shape as `Mesh.cell_sets_dict` for the reasons given in the opening paragraph.

**Comment by nschloe** [comment]
Towards the dream:

Let's add a command-line option to `meshio-convert`, `--int-data-to-sets name1 name2` which converts all given point and cell int data array to point/cell sets (and _all_ if no names are given). If not given, no conversion takes place (and some data might not make it into the other file format, because it cannot deal with cell data or so).
