### ISSUE TITLE
Windows formatted GMsh file cannot be loaded

### ISSUE THREAD

**Issue by SteveDoyle2** [nschloe/meshio#939]
I'm having a same problem to #929 (can't find the $Element section), but for a different model (see attached).  The attached files are *.msh files.

[example_linux.txt](https://github.com/nschloe/meshio/files/5314261/example_linux.txt)
[example_windows.txt](https://github.com/nschloe/meshio/files/5314262/example_windows.txt)

    import meshio
    geom = meshio.read("example_windows.msh")

With the newest version I simply get:

```
Traceback (most recent call last):
  File "gmsh_to_nastran.py", line 154, in <module>
    main()
  File "gmsh_to_nastran.py", line 146, in main
    make_geometry(gmsh_filename, nastran_filename)
  File "gmsh_to_nastran.py", line 150, in make_geometry
    geom = meshio.read(mesh_filename, file_format=None)
  File "C:\Python37\lib\site-packages\meshio\_helpers.py", line 68, in read
    return reader_map[file_format](filename)
  File "C:\Python37\lib\site-packages\meshio\gmsh\main.py", line 19, in read
    mesh = read_buffer(f)
  File "C:\Python37\lib\site-packages\meshio\gmsh\main.py", line 48, in read_buffer
    return reader.read_buffer(f, is_ascii, data_size)
  File "C:\Python37\lib\site-packages\meshio\gmsh\_gmsh41.py", line 59, in read_buffer
    raise ReadError()
meshio._exceptions.ReadError
```

I think the core of the issue is that the read uses "rb" instead of "r".
```
def read(filename):
    """Reads a Gmsh msh file."""
    filename = pathlib.Path(filename)
    with open(filename.as_posix(), "rb") as f:
        mesh = read_buffer(f)
    return mesh
```

I'm new to the GMsh format, but my guess is that's because the binary option is handled with the same function instead of restarting the reader with the "r" option.  There's probably another way to do it too.

**Comment by gdmcbain** [comment]
I am getting a `ReadError` with `examples_windows.txt`, on Ubuntu 20.04.1 LTS, like yours, but it's not the same as the `ReadError` in #929.

> can't find the $Element section

It does actually correctly return from

https://github.com/nschloe/meshio/blob/b6cb61805bb9cf4b51d9514dbefbf69bb5b0c108/meshio/gmsh/_gmsh41.py#L69-L71

The problem is that after that, back at 

https://github.com/nschloe/meshio/blob/b6cb61805bb9cf4b51d9514dbefbf69bb5b0c108/meshio/gmsh/_gmsh41.py#L55

`line` is `"\r"` and so `not line` is `False`.

Maybe the logic of 

https://github.com/nschloe/meshio/blob/b6cb61805bb9cf4b51d9514dbefbf69bb5b0c108/meshio/gmsh/_gmsh41.py#L53-L59

needs rethinking.

**Comment by gdmcbain** [comment]
I'm wondering whether rather there's something wrong with your [`example_windows.txt`](https://github.com/nschloe/meshio/files/5314262/example_windows.txt).  Do you know how it was generated?  Was it generated by Gmsh?  When I generate a MSH 4.1 file with Gmsh 4.6.0 under MS-Windows 10, it ends like (running it through `tail -2 | od -c` back on Linux):
```
0000000   3   3       3   1       3      \r  \n   $   E   n   d   E   l
0000020   e   m   e   n   t   s  \r  \n
0000030
```
but `tail -2 example_windows.msh | od -c` gives
```
0000000   $   E   n   d   E   l   e   m   e   n   t   s  \r  \n  \r
0000017
```

If the trailing "\r" is removed from your file, `meshio.read` is successful.

**Comment by SteveDoyle2** [comment]
So after I found the #929, I updated the version of meshio to 4.2.2.  Unfortunately, I'm not sure which version of meshio I had previously.

It was generated from this (rename to example.geo).  It's a stock example.
[example.geo.txt](https://github.com/nschloe/meshio/files/5315531/example.geo.txt)

using:

`gmsh example.geo -3
`
My version of gmsh is 4.6.0 (at least in the gui).

**Comment by SteveDoyle2** [comment]
To be clear, I'm getting the same empty line error that you are.  I had looked at the code and hadn't seen:

     if line[0] != "$": 
         raise ReadError() 

in the previous version.

**Comment by gdmcbain** [comment]
The issue appears to me to be why `example_windows.txt` ends with a line containing nothing but `\r`.  When I run `gmsh example.geo -3` on my MS-Windows 10 machine with Gmsh, the resulting `examples.msh` doesn't have that.  I've compared the resulting `example.msh` with `examples_windows.txt` in VS Code and they're identical up to line 25061 `$EndElements` but then `examples_windows.txt` has that spurious extra `\r` line.

The Gmsh here is 4.7.0-git-3346eafac (obtained with `pip install gmsh-dev` &mdash; I'm only using such a fresh one because of [gmsh#1007](https://gitlab.onelab.info/gmsh/gmsh/-/issues/1007)).

**Comment by nschloe** [comment]
I can also reproduce the error. It doesn't matter much how the file was created as long as it's legal (aka gmsh itself can read it) -- and that seems to be the case. I've never seen files ending in carriage returns only, but I'll play around a bit.

**Comment by nschloe** [comment]
Iterating over the file like
```python
with open("example_windows.msh") as f:
    while True:
        line = f.readline()
        print(repr(line))
        if not line:
            break
```
works as expected.
```
[...]
'$EndElements\n'
'\n'
''
```

**Comment by nschloe** [comment]
Iterating in binary mode also works:
```python
with open("example_windows.msh", "rb") as f:
    while True:
        line = f.readline().decode("utf-8")
        print(repr(line))
        if not line:
            break
```
```
[...]
'$EndElements\r\n'
'\r'
''
```

**Comment by SteveDoyle2** [comment]
Thank you!
