### ISSUE TITLE
zarr I/O

### ISSUE THREAD

**Issue by glyg** [nschloe/meshio#957]
Hi,

I'm planning on using `meshio` for the [tyssue](https://github.com/damcb/tyssue)  library and am also interested in using `zarr` as a storage format. Searching for meshes and zarr, I saw that @nschloe [was already investigating this](https://github.com/zarr-developers/zarr-python/issues/519)!  

Furthermore, folks at [openmicoscopy](https://github.com/ome/ome-zarr-py) and the microscopy community in general is interested in storing mesh data (essentially from 3D segmentation or iso-intensity curves). 

So I was wondering whether you already have a working example for storing meshes as zarr arrays and if this could be turned into a common specification.

Thanks for the input,

Guillaume

**Comment by nschloe** [comment]
zarr is not a mesh format, it's a container format much like XML or CSV. You can store _anything_ in there. If you want the data to represent a mesh, you'll have to create your own zarr-based mesh format. Not sure if this is worth it.

**Comment by glyg** [comment]
Thanks for the quick answer @nschloe !
I understand zarr is a container, but as there is an effort in the microscopy community to standardize data storage (for images), I wanted to know if you had tried that / had ideas on the store structuring, and avoid doing "my own" format. I feel the effort is not that important given the simplicity of the zarr spec itself.

I tend to generate biggish data (3D meshes that evolve in time) and the absence of proper concurrent access in hdf5 is  starting to be an hindrance.

I guess reflecting closely the meshio API already provides some kind of common ground.

**Comment by nschloe** [comment]
> is an effort in the microscopy community to standardize data storage (for images)

I would _always_ use an existing format. If you think that the existing formats don't fit your case, I'd recommend thinking again until you find they do. :) For example, I have never heard of a case where disk i/o is the bottleneck of an application. Most of the time, you load a mesh into memory, and _then_ the heavy lifting starts: Solving a PDE, display the mesh, etc.

I say this because inventing a mesh format is hard _and_, if you're lucky enough that someone uses your format, you subscribe to a lifetime of support for the format, even you yourself don't use it anymore in 20 years.

It's good that you're looking toward zarr, but really I'd try to push the microscopy community to an existing format. Just think of the ecosystem support alone.

**Comment by nschloe** [comment]
Anyway, let's close this, it's not a meshio issue. We can continue the discussion there though.

**Comment by glyg** [comment]
Thanks for the insight, I agree with you that new formats are hell.

The concurrent access is not for performance reasons - it's that I want to look into the generated meshes while the simulations are running). 

For microscopy images, the need arise from the defaults of the existing standard (tiff) and the need to store other types of data like Region Of Interest, and meshes, conjointly with the images. 

Anyway maybe what I want to do is to _implement_ an existing format specification with zarr as a backend, if that makes any kind of sense?

Thanks again, those are always good warnings to hear:

![xkcd standards](https://imgs.xkcd.com/comics/standards.png)
