### ISSUE TITLE
How to combine two mesh file.

### ISSUE THREAD

**Issue by g873249824** [nschloe/meshio#964]
I want to combine two sets like A1,A2,A3.... B1,B2,B3..... to generate the file C1,C2,C3.... that contain the former.
How can i do it in a fast like shell script or bat script.

Best regards

**Comment by nschloe** [comment]
Using a Python script, you can read the meshes, combine them at will, and write out the result. Check the main readme for instructions.

**Comment by g873249824** [comment]
Thank you very mesh. I got that.

**Comment by g873249824** [comment]
can i get an example for that? I have tried several times but failed.

**Comment by nschloe** [comment]
What have you tried exactly? Let me see some code.

**Comment by g873249824** [comment]
sorry.I cannot submit the vtk file.
I have two vtk files.
`PS D:\Desktop> meshio-info 1.vtk 

<meshio mesh object>
  Number of points: 5892
  Number of cells:
    triangle: 11363
  Point data: fixed
  Cell data: Quality`

`PS D:\Desktop> meshio-info 3.vtk

<meshio mesh object>
  Number of points: 281
  Number of cells:
    quad: 260`

mesh1=meshio.read("1.vtk")
mesh3=meshio.read("1.vtk")

there is no problem until then .
i have tried meshio.write_points_cells("meshtest.vtk",[mesh1.points mesh3.points] ,[mesh3.cells mesh1.cells] ) or somethin like that,i have tried meshio.write_points_cells("meshtest.vtk",mesh1.points,mesh1.cells,point_data=mesh3.points,cells_data=mesh3.cells ).

and meshio.Mesh([mesh1.points mesh3.points] ,[mesh3.cells mesh1.cells]).

Sorry , I amn't familiar with the usage of the functions.

Best regards

**Comment by nschloe** [comment]
Okay yeah, it doesn't work like that. The README gives examples on how to use `write_points_cells()`. In your case, it's getting a little messy because you need to merge two point arrays, and two cells block lists. This includes updating the cell block indices for the second block etc.

From your code examples, it seems to me that your are not familiar enough with meshio or Python for that matter. If this is a problem you need solved, feel free to contact me privately for rates.

**Comment by g873249824** [comment]
OK, I understand that. I thought it can do this automaticly. I understand that ,I need to reorder the idex of vertics and append the points set and ceels set.
